IMPORTING LIBRARIES


In [16]:
import numpy as np
import torch

TIME COMPARISON BETWEEN LIST, NUMPY ARRAYS AND PYTORCH TENSORS

In [31]:
import time

size = 1_000_000

# Python Lists
list_a = list(range(size))
list_b = list(range(size))

# NumPy Arrays
np_a = np.arange(size)
np_b = np.arange(size)

# PyTorch Tensors
pt_a = torch.arange(size)
pt_b = torch.arange(size)


# ----------- List Multiplication -----------
start = time.time()
list_mul = [list_a[i] * list_b[i] for i in range(size)]
end = time.time()
print("List Multiplication Time:", end - start, "seconds")

# ----------- NumPy Multiplication -----------
start = time.time()
np_mul = np_a * np_b
end = time.time()
print("NumPy Multiplication Time:", end - start, "seconds")

# ----------- PyTorch Multiplication -----------
start = time.time()
pt_mul = pt_a * pt_b
end = time.time()
print("PyTorch Multiplication Time:", end - start, "seconds")

List Multiplication Time: 0.21637725830078125 seconds
NumPy Multiplication Time: 0.0036127567291259766 seconds
PyTorch Multiplication Time: 0.002659320831298828 seconds


CREATING 1D,2D AND 3D TENSORS


In [18]:
# NumPy Tensors
np_1d = np.array([1, 2, 3, 4])
np_2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
np_3d = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

# PyTorch Tensors
pt_1d = torch.tensor([1, 2, 3, 4])
pt_2d = torch.tensor([[1, 2, 3],
                      [4, 5, 6]])
pt_3d = torch.tensor([[[1, 2], [3, 4]],
                      [[5, 6], [7, 8]]])

print("NumPy 1D Tensor:\n", np_1d)
print("\nNumPy 2D Tensor:\n", np_2d)
print("\nNumPy 3D Tensor:\n", np_3d)

print("\nPyTorch 1D Tensor:\n", pt_1d)
print("\nPyTorch 2D Tensor:\n", pt_2d)
print("\nPyTorch 3D Tensor:\n", pt_3d)

NumPy 1D Tensor:
 [1 2 3 4]

NumPy 2D Tensor:
 [[1 2 3]
 [4 5 6]]

NumPy 3D Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

PyTorch 1D Tensor:
 tensor([1, 2, 3, 4])

PyTorch 2D Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])

PyTorch 3D Tensor:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


ELEMENT WISE OPERATIONS


In [19]:
# NumPy Element-wise Operations
np_a = np.array([1, 2, 3])
np_b = np.array([4, 5, 6])

print("NumPy Addition:", np_a + np_b)
print("NumPy Multiplication:", np_a * np_b)

# PyTorch Element-wise Operations
pt_a = torch.tensor([1, 2, 3])
pt_b = torch.tensor([4, 5, 6])

print("\nPyTorch Addition:", pt_a + pt_b)
print("PyTorch Multiplication:", pt_a * pt_b)

NumPy Addition: [5 7 9]
NumPy Multiplication: [ 4 10 18]

PyTorch Addition: tensor([5, 7, 9])
PyTorch Multiplication: tensor([ 4, 10, 18])


INDEXING AND SLICING OPERATIONS


In [20]:
# NumPy Indexing and Slicing
print("NumPy Element [0,1]:", np_2d[0, 1])
print("NumPy First Row:", np_2d[0])
print("NumPy Column Slice:\n", np_2d[:, 1:3])


# PyTorch Indexing and Slicing
print("\nPyTorch Element [1,1]:", pt_2d[1, 1])
print("PyTorch Second Row:", pt_2d[0])
print("PyTorch Column Slice:\n", pt_2d[:, 1:3])

NumPy Element [0,1]: 2
NumPy First Row: [1 2 3]
NumPy Column Slice:
 [[2 3]
 [5 6]]

PyTorch Element [1,1]: tensor(5)
PyTorch Second Row: tensor([1, 2, 3])
PyTorch Column Slice:
 tensor([[2, 3],
        [5, 6]])


BOOLEAN MASKING AND SUB-TENSOR EXTRACTION

In [21]:
#NumPy Boolean Masking
mask_np = np_2d > 3
print("NumPy Boolean Mask:\n", mask_np)
print("NumPy Masked Values:", np_2d[mask_np])

# PyTorch Boolean Masking
mask_pt = pt_2d > 3
print("\nPyTorch Boolean Mask:\n", mask_pt)
print("PyTorch Masked Values:", pt_2d[mask_pt])

NumPy Boolean Mask:
 [[False False False]
 [ True  True  True]]
NumPy Masked Values: [4 5 6]

PyTorch Boolean Mask:
 tensor([[False, False, False],
        [ True,  True,  True]])
PyTorch Masked Values: tensor([4, 5, 6])


PyTorch: view(), reshape(), unsqueeze(), squeeze()

In [22]:
x = torch.arange(1, 7)  # Tensor: [1, 2, 3, 4, 5, 6]
print("Original Tensor:", x)

# view()
x_view = x.view(2, 3)
print("\nView (2x3):\n", x_view)

# reshape()
x_reshape = x.reshape(3, 2)
print("\nReshape (3x2):\n", x_reshape)

# unsqueeze()
x_unsq = x.unsqueeze(0)
print("\nUnsqueeze (dim=0):\n", x_unsq)

# squeeze()
x_sq = x_unsq.squeeze()
print("\nSqueeze:\n", x_sq)

Original Tensor: tensor([1, 2, 3, 4, 5, 6])

View (2x3):
 tensor([[1, 2, 3],
        [4, 5, 6]])

Reshape (3x2):
 tensor([[1, 2],
        [3, 4],
        [5, 6]])

Unsqueeze (dim=0):
 tensor([[1, 2, 3, 4, 5, 6]])

Squeeze:
 tensor([1, 2, 3, 4, 5, 6])


COMPARING RESHAPE IN NUMPY AND PYTORCH


In [23]:
# NumPy reshape
np_x = np.array([1, 2, 3, 4, 5, 6])
np_reshape = np_x.reshape(2, 3)

print("NumPy reshape (2x3):\n", np_reshape)

# PyTorch reshape
pt_x = torch.tensor([1, 2, 3, 4, 5, 6])
pt_reshape = pt_x.reshape(2, 3)

print("\nPyTorch reshape (2x3):\n", pt_reshape)

NumPy reshape (2x3):
 [[1 2 3]
 [4 5 6]]

PyTorch reshape (2x3):
 tensor([[1, 2, 3],
        [4, 5, 6]])


BROADCASTING


In [24]:
# NumPy Broadcasting Example
np_m = np.array([[1, 2, 3],
                 [4, 5, 6]])
np_v = np.array([10, 20, 30])

print("NumPy Broadcasting Result:\n", np_m + np_v)

# PyTorch Broadcasting Example
pt_m = torch.tensor([[1, 2, 3],
                      [4, 5, 6]])
pt_v = torch.tensor([10, 20, 30])

print("\nPyTorch Broadcasting Result:\n", pt_m + pt_v)

NumPy Broadcasting Result:
 [[11 22 33]
 [14 25 36]]

PyTorch Broadcasting Result:
 tensor([[11, 22, 33],
        [14, 25, 36]])


IN-PLACE vs OUT-PLACE OF OPERATIONS

In [25]:
# NumPy Out-of-place Operation
np_a = np.array([1, 2, 3])
np_b = np_a + 5

print("NumPy Original Array:", np_a)
print("NumPy Out-of-place Result:", np_b)

# NumPy In-place Operation
np_a += 5
print("NumPy After In-place += :", np_a)



# PyTorch Out-of-place Operation
a = torch.tensor([1, 2, 3], dtype=torch.float32)
b = a + 5

print("\nPyTorch Original Tensor a:", a)
print("PyTorch Out-of-place Result b:", b)

# PyTorch In-place Operation
a.add_(5)
print("PyTorch After In-place add_():", a)



NumPy Original Array: [1 2 3]
NumPy Out-of-place Result: [6 7 8]
NumPy After In-place += : [6 7 8]

PyTorch Original Tensor a: tensor([1., 2., 3.])
PyTorch Out-of-place Result b: tensor([6., 7., 8.])
PyTorch After In-place add_(): tensor([6., 7., 8.])
